### ISSUE TITLE
Potential Error in Exercise 3.5.12 Solution

### ISSUE THREAD

**Issue by Friendseeker** [tling04/Analysis#3]
<img width="928" alt="Screen Shot 2022-08-26 at 6 12 11 PM" src="https://user-images.githubusercontent.com/66892505/187008504-eb3a7665-794e-4606-964e-a58060c9f423.png">

<img width="903" alt="Screen Shot 2022-08-26 at 6 14 21 PM" src="https://user-images.githubusercontent.com/66892505/187008577-de2ceaf0-f9e3-4366-8d70-23cbff07472f.png">

While your inductive argument showed that at least one function exists and is a candidate for $a_{N\mathtt{++}}$, you do not rule out that another function $r_{N\mathtt{++}}: \{n \in \mathbb{N}: n \leq N\mathtt{++}\} \rightarrow \mathbb{N}$ may also exist s.t. $r_{N\mathtt{++}}(0) = c$ and $r_{N\mathtt{++}}(n\mathtt{++}) = f(n, r_{N\mathtt{++}}(n))$. Hence, uniqueness of each $a_{N}$ is not justified in your solution.

**Comment by tling04** [comment]
<img width="609" alt="0" src="https://user-images.githubusercontent.com/44835660/187010397-454dc137-8d6d-4755-ba2d-66a812fb2fa5.png">
<img width="679" alt=" " src="https://user-images.githubusercontent.com/44835660/187010398-a2b72d70-12b4-43c1-b511-e53815466016.png">
Thank you for pointing this out! There was a typo in the purpose of induction - I was using it to show that at least one function exists. The uniqueness part was justified in the last paragraph.

**Comment by Friendseeker** [comment]
<img width="682" alt="Screen Shot 2022-08-26 at 9 05 03 PM" src="https://user-images.githubusercontent.com/66892505/187013679-41ee86f3-997e-4812-9698-76a95c4033eb.png">

**Comment by tling04** [comment]
Thank you so much for the thorough explanation! I mixed up the uniqueness of $a_N$ and the uniqueness of $a$. The solution has been updated.
